### PR TITLE
Redirect based on email address

### PR DESCRIPTION
**Pull request by sangeethailango**
This PR will redirect the user, based on their email address.

### CODE REVIEW

**Comment by sangeethailango** [comment]
Fixed #2

**Comment by sangeethailango** [comment]
Screenshot from 2024-02-22 14-47-00

**Comment by sakthibalan15** [comment]
- [ ] If I click proceed button without checking approved option the email address is deleted. The email value should retain.
- [ ] The visitor form, booking form and preview value should be shown in a single URL route. (render live view component)

**Comment by sangeethailango** [comment]
@sakthibalan15 Created forms in a single router path.

**Comment by sangeethailango** [comment]
- [ ] Save the data in the database
- [ ] Report page

**Pull request merged**
